import { PrismaClient, ProductCategory, ProductBadge } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Clear existing data
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.address.deleteMany();
  await prisma.customer.deleteMany();
  await prisma.product.deleteMany();
  await prisma.chickenBreed.deleteMany();
  await prisma.newsletterSubscriber.deleteMany();
  await prisma.contactMessage.deleteMany();

  // Seed Products
  const products = [
    // Œufs frais
    {
      name: 'Œufs Bio - Boîte de 6',
      slug: 'oeufs-bio-boite-6',
      category: 'oeufs_frais' as ProductCategory,
      description: 'Nos œufs bio proviennent de poules élevées en plein air, nourries exclusivement avec des aliments certifiés agriculture biologique.',
      shortDescription: 'Œufs frais de poules élevées en plein air, certifiés bio.',
      price: 20000,
      images: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600'],
      inStock: true,
      stockQuantity: 50,
      badges: ['bio', 'plein_air'] as ProductBadge[],
      characteristics: ['Certification Agriculture Biologique AB', 'Poules élevées en plein air', 'Ramassage quotidien', 'Calibre moyen à gros'],
      quantity: 6,
    },
    {
      name: 'Œufs Bio - Boîte de 12',
      slug: 'oeufs-bio-boite-12',
      category: 'oeufs_frais' as ProductCategory,
      description: 'Notre boîte familiale de 12 œufs bio, idéale pour les familles ou les amateurs de pâtisserie.',
      shortDescription: 'Format familial de nos délicieux œufs bio.',
      price: 38000,
      originalPrice: 40000,
      images: ['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600'],
      inStock: true,
      stockQuantity: 35,
      badges: ['bio', 'plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['Certification Agriculture Biologique AB', 'Poules élevées en plein air', 'Économie par rapport à la boîte de 6'],
      quantity: 12,
    },
    {
      name: 'Plateau 30 œufs Plein Air',
      slug: 'plateau-30-oeufs-plein-air',
      category: 'oeufs_frais' as ProductCategory,
      description: 'Le plateau idéal pour les grandes familles ou les professionnels.',
      shortDescription: 'Grand plateau de 30 œufs pour les familles nombreuses.',
      price: 81000,
      images: ['https://images.unsplash.com/photo-1569288052389-dac9b0ac9eac?w=600'],
      inStock: true,
      stockQuantity: 20,
      badges: ['plein_air'] as ProductBadge[],
      characteristics: ['Poules élevées en plein air', 'Format économique', 'Calibre moyen'],
      quantity: 30,
    },
    // Œufs fécondés
    {
      name: 'Œufs fécondés Marans',
      slug: 'oeufs-fecondes-marans',
      category: 'oeufs_fecondes' as ProductCategory,
      description: 'Œufs fécondés de notre lignée de Marans noire cuivrée, célèbre pour ses œufs extra-roux.',
      shortDescription: 'Œufs fécondés pour faire naître vos propres Marans.',
      price: 15500,
      images: ['https://images.unsplash.com/photo-1569288052389-dac9b0ac9eac?w=600'],
      inStock: true,
      stockQuantity: 24,
      badges: ['plein_air'] as ProductBadge[],
      characteristics: ['Race Marans noire cuivrée', 'Taux de fécondité > 90%', 'Guide d\'incubation inclus'],
      race: 'Marans',
      eggColor: 'Roux foncé',
    },
    {
      name: 'Œufs fécondés Sussex',
      slug: 'oeufs-fecondes-sussex',
      category: 'oeufs_fecondes' as ProductCategory,
      description: 'Œufs fécondés de Sussex herminée, une race anglaise réputée pour sa docilité.',
      shortDescription: 'Œufs fécondés Sussex, idéal pour débutants.',
      price: 13500,
      images: ['https://images.unsplash.com/photo-1569288052389-dac9b0ac9eac?w=600'],
      inStock: true,
      stockQuantity: 18,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['Race Sussex herminée', 'Caractère docile', 'Parfaite pour débuter'],
      race: 'Sussex',
      eggColor: 'Crème',
    },
    {
      name: 'Œufs fécondés Araucana',
      slug: 'oeufs-fecondes-araucana',
      category: 'oeufs_fecondes' as ProductCategory,
      description: 'Découvrez les fameux œufs bleus ! L\'Araucana est une race chilienne unique.',
      shortDescription: 'Les fameux œufs bleus pour votre basse-cour.',
      price: 18000,
      images: ['https://images.unsplash.com/photo-1569288052389-dac9b0ac9eac?w=600'],
      inStock: true,
      stockQuantity: 12,
      badges: ['nouveau'] as ProductBadge[],
      characteristics: ['Œufs naturellement bleus', 'Race originaire du Chili', 'Très rustique'],
      race: 'Araucana',
      eggColor: 'Bleu-vert',
    },
    // Poules vivantes
    {
      name: 'Poule Rousse Pondeuse',
      slug: 'poule-rousse-pondeuse',
      category: 'poules' as ProductCategory,
      description: 'Notre poule rousse fermière est une valeur sûre ! Pondeuse exceptionnelle.',
      shortDescription: 'La poule pondeuse par excellence, productive et docile.',
      price: 81000,
      images: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600'],
      inStock: true,
      stockQuantity: 25,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['250-300 œufs par an', 'Ponte dès 20-22 semaines', 'Caractère docile'],
      race: 'Rousse fermière',
      eggColor: 'Brun',
    },
    {
      name: 'Poule Sussex Herminée',
      slug: 'poule-sussex-herminee',
      category: 'poules' as ProductCategory,
      description: 'La Sussex herminée est une magnifique poule au plumage blanc avec le camail noir.',
      shortDescription: 'Élégante poule anglaise au plumage blanc et noir.',
      price: 112500,
      images: ['https://images.unsplash.com/photo-1598965402089-897ce52e8355?w=600'],
      inStock: true,
      stockQuantity: 15,
      badges: ['plein_air'] as ProductBadge[],
      characteristics: ['200-250 œufs par an', 'Plumage blanc herminé', 'Très docile'],
      race: 'Sussex',
      eggColor: 'Crème',
    },
    {
      name: 'Poule Marans Noire Cuivrée',
      slug: 'poule-marans-noire-cuivree',
      category: 'poules' as ProductCategory,
      description: 'La Marans est LA poule française par excellence, célèbre pour ses œufs "extra-roux".',
      shortDescription: 'La reine des œufs extra-roux, plumage noir cuivré.',
      price: 135000,
      images: ['https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=600'],
      inStock: true,
      stockQuantity: 12,
      badges: ['plein_air', 'populaire'] as ProductBadge[],
      characteristics: ['150-200 œufs extra-roux par an', 'Race française du terroir', 'Rustique'],
      race: 'Marans',
      eggColor: 'Roux foncé',
    },
    {
      name: 'Poule Araucana',
      slug: 'poule-araucana',
      category: 'poules' as ProductCategory,
      description: 'L\'Araucana vous surprendra avec ses œufs naturellement bleu-vert !',
      shortDescription: 'La poule aux œufs bleus, originaire du Chili.',
      price: 157500,
      images: ['https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600'],
      inStock: true,
      stockQuantity: 8,
      badges: ['nouveau', 'plein_air'] as ProductBadge[],
      characteristics: ['150-180 œufs bleus par an', 'Sans croupion', 'Très rustique'],
      race: 'Araucana',
      eggColor: 'Bleu-vert',
    },
    {
      name: 'Poule Soie Blanche',
      slug: 'poule-soie-blanche',
      category: 'poules' as ProductCategory,
      description: 'La poule Soie est irrésistible avec son plumage duveteux qui ressemble à de la soie !',
      shortDescription: 'Adorable poule d\'ornement au plumage soyeux.',
      price: 180000,
      images: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600'],
      inStock: true,
      stockQuantity: 6,
      badges: ['nouveau'] as ProductBadge[],
      characteristics: ['80-100 œufs par an', 'Plumage soyeux unique', 'Excellente couveuse'],
      race: 'Soie',
      eggColor: 'Crème',
    },
    // Accessoires
    {
      name: 'Poulailler Bois 4-6 Poules',
      slug: 'poulailler-bois-4-6-poules',
      category: 'accessoires' as ProductCategory,
      description: 'Poulailler en bois traité autoclave, parfait pour 4 à 6 poules.',
      shortDescription: 'Poulailler robuste en bois pour 4 à 6 poules.',
      price: 850000,
      images: ['https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600'],
      inStock: true,
      stockQuantity: 5,
      badges: [] as ProductBadge[],
      characteristics: ['Capacité : 4-6 poules', 'Bois traité autoclave', 'Toit bitumé imperméable'],
      dimensions: '150x80x100 cm',
    },
    {
      name: 'Aliment Poules Pondeuses Bio 20kg',
      slug: 'aliment-poules-pondeuses-bio-20kg',
      category: 'accessoires' as ProductCategory,
      description: 'Aliment complet bio pour poules pondeuses, formulé pour une ponte optimale.',
      shortDescription: 'Aliment complet bio pour une ponte optimale.',
      price: 112000,
      images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600'],
      inStock: true,
      stockQuantity: 40,
      badges: ['bio', 'populaire'] as ProductBadge[],
      characteristics: ['Certifié Agriculture Biologique', 'Sans OGM', 'Riche en calcium'],
      weight: '20 kg',
    },
    {
      name: 'Abreuvoir Automatique 5L',
      slug: 'abreuvoir-automatique-5l',
      category: 'accessoires' as ProductCategory,
      description: 'Abreuvoir à réserve de 5 litres avec niveau constant.',
      shortDescription: 'Abreuvoir pratique à remplissage facile.',
      price: 58000,
      images: ['https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?w=600'],
      inStock: true,
      stockQuantity: 35,
      badges: [] as ProductBadge[],
      characteristics: ['Capacité 5 litres', 'Niveau d\'eau constant', 'Facile à nettoyer'],
    },
    {
      name: 'Mangeoire Anti-Gaspillage 10kg',
      slug: 'mangeoire-anti-gaspillage-10kg',
      category: 'accessoires' as ProductCategory,
      description: 'Mangeoire avec grille anti-gaspillage qui empêche les poules de gratter.',
      shortDescription: 'Mangeoire grande capacité anti-gaspillage.',
      price: 135000,
      images: ['https://images.unsplash.com/photo-1606567595334-d39972c85dfd?w=600'],
      inStock: true,
      stockQuantity: 20,
      badges: ['populaire'] as ProductBadge[],
      characteristics: ['Capacité 10 kg', 'Grille anti-gaspillage', 'Couvercle étanche'],
    },
  ];

  for (const product of products) {
    await prisma.product.create({ data: product });
  }
  console.log(`Created ${products.length} products`);

  // Seed Chicken Breeds
  const chickenBreeds = [
    {
      name: 'Marans Noire Cuivrée',
      slug: 'marans-noire-cuivree',
      image: 'https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=600',
      galleryImages: ['https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=600'],
      eggColor: 'Roux foncé (chocolat)',
      eggColorHex: '#8B4513',
      temperament: 'Calme et docile',
      productivity: 'moyenne',
      productivityNumber: 65,
      eggsPerYear: '150-200',
      description: 'La Marans est une race française originaire de la ville de Marans en Charente-Maritime.',
      characteristics: ['Œufs d\'un beau roux foncé', 'Plumage noir aux reflets cuivrés', 'Excellente résistance au froid'],
      whyChoose: 'Choisissez la Marans pour la beauté incomparable de ses œufs chocolat !',
      origin: 'France (Charente-Maritime)',
      weight: 'Coq: 3,5-4 kg / Poule: 2,5-3 kg',
      available: true,
      price: 135000,
    },
    {
      name: 'Sussex Herminée',
      slug: 'sussex-herminee',
      image: 'https://images.unsplash.com/photo-1598965402089-897ce52e8355?w=600',
      galleryImages: ['https://images.unsplash.com/photo-1598965402089-897ce52e8355?w=600'],
      eggColor: 'Crème à rosé',
      eggColorHex: '#FFF8DC',
      temperament: 'Très docile et sociable',
      productivity: 'élevée',
      productivityNumber: 85,
      eggsPerYear: '200-250',
      description: 'La Sussex est une race anglaise ancestrale. La variété herminée est la plus élégante.',
      characteristics: ['Plumage blanc avec camail noir', 'Excellente pondeuse', 'Très docile'],
      whyChoose: 'La Sussex herminée est le choix parfait pour les familles !',
      origin: 'Angleterre (Sussex)',
      weight: 'Coq: 4 kg / Poule: 3-3,5 kg',
      available: true,
      price: 112500,
    },
    {
      name: 'Poule Rousse Fermière',
      slug: 'poule-rousse-fermiere',
      image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600',
      galleryImages: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600'],
      eggColor: 'Brun clair',
      eggColorHex: '#DEB887',
      temperament: 'Active et curieuse',
      productivity: 'très-élevée',
      productivityNumber: 95,
      eggsPerYear: '250-300',
      description: 'La poule rousse fermière est LA poule pondeuse par excellence !',
      characteristics: ['Championne de ponte', 'Très rustique', 'Facile à élever pour les débutants'],
      whyChoose: 'La rousse fermière est faite pour vous si vous cherchez une pondeuse efficace !',
      origin: 'Hybride (sélection française)',
      weight: 'Poule: 2,5-3 kg',
      available: true,
      price: 81000,
    },
    {
      name: 'Araucana',
      slug: 'araucana',
      image: 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600',
      galleryImages: ['https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=600'],
      eggColor: 'Bleu-vert',
      eggColorHex: '#87CEEB',
      temperament: 'Vive et indépendante',
      productivity: 'moyenne',
      productivityNumber: 60,
      eggsPerYear: '150-180',
      description: 'L\'Araucana est originaire du Chili. Elle pond des œufs naturellement bleu-vert !',
      characteristics: ['Œufs naturellement bleu-vert', 'Sans croupion', 'Très rustique'],
      whyChoose: 'L\'Araucana est un choix original pour les amateurs de diversité !',
      origin: 'Chili (Amérique du Sud)',
      weight: 'Coq: 2,5 kg / Poule: 2 kg',
      available: true,
      price: 157500,
    },
    {
      name: 'Poule Soie (Nègre-Soie)',
      slug: 'poule-soie',
      image: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600',
      galleryImages: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600'],
      eggColor: 'Crème rosé',
      eggColorHex: '#FFE4C4',
      temperament: 'Très docile et câline',
      productivity: 'faible',
      productivityNumber: 30,
      eggsPerYear: '80-100',
      description: 'La poule Soie est unique au monde avec son plumage duveteux qui ressemble à de la soie !',
      characteristics: ['Plumage soyeux unique', 'Peau et os noirs', '5 doigts', 'Excellente couveuse'],
      whyChoose: 'La poule Soie est parfaite si vous cherchez un animal de compagnie !',
      origin: 'Chine (Asie)',
      weight: 'Coq: 1,5 kg / Poule: 1-1,2 kg',
      available: true,
      price: 180000,
    },
  ];

  for (const breed of chickenBreeds) {
    await prisma.chickenBreed.create({ data: breed });
  }
  console.log(`Created ${chickenBreeds.length} chicken breeds`);

  console.log('Seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
